const API_RESPONSE_ACCOUNTS = 'cloud_account_overviews';
const API_RESPONSE_ACCOUNTS_ID = 'id';
const API_RESPONSE_ACCOUNTS_IMAGES = 'images';
const API_RESPONSE_ACCOUNTS_INSTANCES = 'instances';
const API_RESPONSE_ACCOUNTS_NAME = 'name';
const API_RESPONSE_ACCOUNTS_OPENSHIFT = 'openshift_instances';
const API_RESPONSE_ACCOUNTS_RHEL = 'rhel_instances';
const API_RESPONSE_ACCOUNTS_START = 'start';
const API_RESPONSE_ACCOUNTS_END = 'end';
const API_RESPONSE_ACCOUNTS_DATE = 'creation_date';
const API_QUERY_START = 'start';
const API_QUERY_END = 'end';
const API_QUERY_NAME = 'name_pattern';

// ToDo: need to go back filter these down, currently have repeats
const API_GET_ACCOUNT_COUNT = 'count';
const API_GET_ACCOUNT_RESULTS = 'results';
const API_ACCOUNT_ARN = 'account_arn';
const API_ACCOUNT_NAME = 'name';
const API_RESOURCE_TYPE = 'resourcetype';
const API_AWS_ACCOUNT_ID = 'aws_account_id';

const apiTypes = {
  API_RESPONSE_ACCOUNTS,
  API_RESPONSE_ACCOUNTS_ID,
  API_RESPONSE_ACCOUNTS_IMAGES,
  API_RESPONSE_ACCOUNTS_INSTANCES,
  API_RESPONSE_ACCOUNTS_NAME,
  API_RESPONSE_ACCOUNTS_OPENSHIFT,
  API_RESPONSE_ACCOUNTS_RHEL,
  API_RESPONSE_ACCOUNTS_START,
  API_RESPONSE_ACCOUNTS_END,
  API_RESPONSE_ACCOUNTS_DATE,
  API_QUERY_START,
  API_QUERY_END,
  API_QUERY_NAME,
  API_GET_ACCOUNT_COUNT,
  API_GET_ACCOUNT_RESULTS,
  API_ACCOUNT_ARN,
  API_ACCOUNT_NAME,
  API_RESOURCE_TYPE,
  API_AWS_ACCOUNT_ID
};

export {
  apiTypes as default,
  apiTypes,
  API_RESPONSE_ACCOUNTS,
  API_RESPONSE_ACCOUNTS_ID,
  API_RESPONSE_ACCOUNTS_IMAGES,
  API_RESPONSE_ACCOUNTS_INSTANCES,
  API_RESPONSE_ACCOUNTS_NAME,
  API_RESPONSE_ACCOUNTS_OPENSHIFT,
  API_RESPONSE_ACCOUNTS_RHEL,
  API_RESPONSE_ACCOUNTS_START,
  API_RESPONSE_ACCOUNTS_END,
  API_RESPONSE_ACCOUNTS_DATE,
  API_QUERY_START,
  API_QUERY_END,
  API_QUERY_NAME,
  API_GET_ACCOUNT_COUNT,
  API_GET_ACCOUNT_RESULTS,
  API_ACCOUNT_ARN,
  API_ACCOUNT_NAME,
  API_RESOURCE_TYPE,
  API_AWS_ACCOUNT_ID
};
