FROM centos:7

RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash - && \
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    yum install nodejs yarn -y

WORKDIR /app
ADD . /app

RUN yarn --production --non-interactive --silent \
    && yarn build >/dev/null
