const ADD_ACCOUNT = 'ADD_ACCOUNT';
const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
const DELETE_ACCOUNTS = 'DELETES_ACCOUNTS';
const GET_ACCOUNT = 'GET_ACCOUNT';
const GET_ACCOUNTS = 'GET_ACCOUNTS';
const ADD_ACCOUNT_WIZARD = 'ADD_ACCOUNT_WIZARD';
const ADD_ACCOUNT_WIZARD_STEPONE = 'ADD_ACCOUNT_WIZARD_STEPONE';
const ADD_ACCOUNT_WIZARD_STEPTWO = 'ADD_ACCOUNT_WIZARD_STEPTWO';
const ADD_ACCOUNT_WIZARD_STEPTHREE = 'ADD_ACCOUNT_WIZARD_STEPTHREE';
const INVALID_ACCOUNT_WIZARD_STEPTHREE = 'INVALID_ACCOUNT_WIZARD_STEPTHREE';
const ADD_ACCOUNT_SHOW = 'CREATE_SOURCE_SHOW';
const EDIT_ACCOUNT_SHOW = 'EDIT_SOURCE_SHOW';
const UPDATE_ACCOUNT_HIDE = 'UPDATE_SOURCE_HIDE';

export {
  ADD_ACCOUNT,
  DELETE_ACCOUNT,
  DELETE_ACCOUNTS,
  GET_ACCOUNT,
  GET_ACCOUNTS,
  ADD_ACCOUNT_WIZARD,
  ADD_ACCOUNT_WIZARD_STEPONE,
  ADD_ACCOUNT_WIZARD_STEPTWO,
  ADD_ACCOUNT_WIZARD_STEPTHREE,
  INVALID_ACCOUNT_WIZARD_STEPTHREE,
  ADD_ACCOUNT_SHOW,
  EDIT_ACCOUNT_SHOW,
  UPDATE_ACCOUNT_HIDE
};
